package cc.emulator.arch.arm.instruction;

import cc.emulator.arch.arm.ArmInstruction;
import cc.emulator.core.cpu.Instruction;

/**
 * STREX
 * Store Register Exclusive calculates an address from a base register value and an immediate offset, stores a word
 * from a register to memory if the executing processor has exclusive access to the memory addressed, and returns a
 * status word that indicates whether this store was performed.
 * For more information about support for shared memory see Synchronization and semaphores on page A3-114. For
 * information about memory accesses see Memory accesses on page A8-294.
 *
 * Encoding T1 ARMv6T2, ARMv7
 *      STREX<c> <Rd>, <Rt>, [<Rn>{, #<imm>}]
 *
 * -------------------------------------------------------------------------------------------------
 * |15 14 13 12|11|10| 9| 8| 7| 6| 5| 4| 3| 2  1  0|15 14|13|12|11|10  9  8| 7| 6| 5| 4| 3  2  1  0|
 * |--------------+--+--+-----------+--|-----------|-----------|-----------------------------------|
 * | 1  1  1  0  1| 0  0| 0| 0| 1| 0| 0|   Rn      |  Rt       |   Rd      |   imm8                |
 * |--------------+--+--+-----------+--|-----------|-----------|-----------------------------------|

 * d = UInt(Rd); t = UInt(Rt); n = UInt(Rn); imm32 = ZeroExtend(imm8:’00’, 32);
 * if d IN {13,15} || t IN {13,15} || n == 15 then UNPREDICTABLE;
 * if d == n || d == t then UNPREDICTABLE;
 *
 * Encoding A1 ARMv6*, ARMv7
 *      STREX<c> <Rd>, <Rt>, [<Rn>]
 *
 * |31 30 29 28|27|26|25|24 23|22|21|20|19 18 17 16|15 14 13 12|11 10  9  8| 7  6  5  4| 3  2  1  0|Instruction Type
 * |-----------|--+--+--+-----------+--|-----------|-----------|-----------------------------------|-----------------
 * | Condition | 0| 0| 0| 1| 1| 0| 0| 0|   Rn      |  Rd       |(1)(1)(1)(1| 1  0  0  1|  Rt       |  STREX
 * |-----------|--+--+--+--+-----------|-----------|-----------|-----------------------------------|-----------------

 * For the case when cond is 0b1111, see Unconditional instructions on page A5-216.
 * d = UInt(Rd); t = UInt(Rt); n = UInt(Rn); imm32 = Zeros(32); // Zero offset
 * if d == 15 || t == 15 || n == 15 then UNPREDICTABLE;
 * if d == n || d == t then UNPREDICTABLE;
 *
 * Assembler syntax
 *  STREX{<c>}{<q>} <Rd>, <Rt>, [<Rn> {, #<imm>}]
 * where:
 *  <c>, <q>    See Standard assembler syntax fields on page A8-287.
 *  <Rd>        The destination register for the returned status value. The value returned is:
 *              0 if the operation updates memory
 *              1 if the operation fails to update memory.
 *  <Rt>        The source register.
 *  <Rn>        The base register. The SP can be used.
 *  <imm>       The immediate offset added to the value of <Rn> to form the address. Values are multiples of 4 in the
 *              range 0-1020 for encoding T1, and 0 for encoding A1. <imm> can be omitted, meaning an offset of 0.
 * Operation
 *  if ConditionPassed() then
 *      EncodingSpecificOperations(); NullCheckIfThumbEE(n);
 *      address = R[n] + imm32;
 *      if ExclusiveMonitorsPass(address,4) then
 *          MemA[address,4] = R[t];
 *          R[d] = ZeroExtend(‘0’, 32);
 *      else
 *          R[d] = ZeroExtend(‘1’, 32);
 * Exceptions
 *  Data Abort.
 *
 * Aborts and alignment
 * If a synchronous Data Abort exception is generated by the execution of this instruction:
 * . memory is not updated
 * . <Rd> is not updated.
 * In ARMv7, a non word-aligned memory address causes an Alignment fault Data Abort exception to be generated,
 * subject to the following rules:
 * . If ExclusiveMonitorsPass() returns TRUE, the exception is generated.
 * . Otherwise, it is IMPLEMENTATION DEFINED whether the exception is generated.
 * If ExclusiveMonitorsPass() returns FALSE and the memory address, if accessed, would generate a synchronous Data
 * Abort exception, it is IMPLEMENTATION DEFINED whether the exception is generated.
 * Note
 * In ARMv6:
 * . If SCTLR.A and SCTLR.U are both 0, a non word-aligned memory address causes UNPREDICTABLE behavior.
 * . Otherwise, the ARMv7 behavior applies.
 *
 *
 * @author Shao Yongqing
 * Date: 2017/10/17.
 */
public class STREX extends StoreRegisterExclusive {
    public STREX(int rawInstruction) {
        super(rawInstruction);
    }
    @Override
    protected int getOp(){
        return 0b1000;
    }

}
